### PR TITLE
Update CustomCircularQueueArray.c

### PR DESCRIPTION
**Pull request by Tejas20-03**

### CODE REVIEW

**Comment by driptanil** [comment]
Let me take a look 👀

**Comment by driptanil** [comment]
@Tejas20-03 Everything works, please make some changes in printing 

- print menu like this:  `1. Enqueue\t2. Dequeue\t3.  Exit\n`

- add `\n` before "Enter your choice" 

- when the queue is empty print `Empty Queue !!!`

- when the queue is full print ` Full Queue !!!`
 
- no need to print "Queue is:" in `display() `

**Comment by Tejas20-03** [comment]
Sure... will do the same... give me a while

**Comment by Tejas20-03** [comment]
Done with all the changes @driptanil

**Comment by driptanil** [comment]
Great Job !!!

**Pull request merged**
